name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: installing 
        run: sudo apt install -y npm && sudo apt install -y nodejs
      - name: starting 
        run: sudo apt install git && git clone https://github.com/Aryangitrepo/test
      - name: real
        run: cd test && npm test
